### Testando a segunda funcionalidade
GET http://localhost:5262

### Testando o cadastro de produtos
POST http://localhost:5262/produto/cadastrar
Content-Type: application/json

{
    "nome": "Água",
    "preco": 6.7,
    "quantidade": 35 
}

### Testando a modificação das informações de um produto disponível
PUT http://localhost:5262/produto/alterar/5323cd8d-f932-4ddf-9db1-bf0aadb53dfa
Content-Type: application/json

{
    "nome": "PS5",
    "preco": 5250,
    "descricao": "Console mais famoso da playstation",
    "quantidade": 32
}

### Testando a listagem de produtos
GET  http://localhost:5262/produto/listar

### Testando a busca por produtos
GET http://localhost:5262/produto/buscar/5323cd8d-f932-4ddf-9db1-bf0aadb53dfa

### Testando a remoção de produtos
DELETE  http://localhost:5262/produto/remover/5323cd8d-f932-4ddf-9db1-bf0aadb53dfa